version: "3"
services:
  web:
    image: nginx
    volumes:
        - "/mnt/nginx/html:/usr/share/nginx/html:ro"
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nginx-net
networks:
  nginx-net:
